version: '3'
services:
  spring-boot-app:
    build: .
    depends_on:
      - mariadb
    network_mode: bridge
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: mySite
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    network_mode: bridge
    ports:
      - "3306:3306"