version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: mySite
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  app:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mySite
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
